architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/exposure.accesswidener")
}

repositories {
    // Forge Config Api Port
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    // Remove the next line if you don't want to depend on the API
    // modApi "dev.architectury:architectury:${rootProject.architectury_version}"

    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")

    modCompileOnlyApi("curse.maven:jade-324717:${jade_fabric_id}")
    modRuntimeOnly("curse.maven:jade-324717:${jade_fabric_id}") { transitive = false }

    //modCompileOnlyApi("dev.latvian.mods:kubejs:${kubejs_version}")

    modCompileOnly("curse.maven:real-camera-851574:5328994")

    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude group: 'net.fabricmc.fabric-api'
    }

//    modCompileOnly("curse.maven:architectury-${architectury_cf_version}")

    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_version}"

}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = mod_id + "-" + project.name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        var path = System.getenv("LOCAL_MAVEN")
        if (path != null) {
            maven {
                name = 'local'
                url = uri(path + "/maven")
            }
        }
    }
}
